version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
  docker: circleci/docker@0.5.13
  go: circleci/go@0.2.0
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: Run tests
          command: go test -coverprofile=coverage.txt -covermode=atomic -v -p 1 ./...
          environment:
            SPRAWL_DATABASE_PATH: /go/src/github.com/sprawl/sprawl/data
      - run:
        name: Install cob
        command: curl -sfL https://raw.githubusercontent.com/knqyf263/cob/master/install.sh | sudo sh -s -- -b /usr/local/bin
      - run:
          name: Run cob
          command: cob
      - codecov/upload:
          file: ./coverage.txt
